FROM node:16

ARG configName=config-aws-ecs

RUN su - && apt update
RUN su - && apt install openssh-server nano htop tree -y

RUN su - && mkdir /root/.ssh 
COPY KYP_TradingBot-Test_DEV.pub /root/.ssh/authorized_keys
RUN su - && echo "PasswordAuthentication no" >> /etc/ssh/sshd_config

WORKDIR /webapps

COPY tsconfig.json historical-backtesting-server/
COPY tsconfig.build.json historical-backtesting-server/
COPY package.json historical-backtesting-server/
COPY nest-cli.json historical-backtesting-server/
COPY src/ historical-backtesting-server/src
COPY config/ historical-backtesting-server/config

WORKDIR /webapps/historical-backtesting-server

COPY .npmrc .npmrc
RUN npm install --legacy-peer-deps --no-optional
RUN rm -f historical-backtesting-server/.npmrc

RUN rm -f config/current.json
COPY config/${configName}.json config/current.json

RUN npm run build

CMD service ssh restart && npm start
EXPOSE 22 4005 40005
