#!/bin/bash

if [ -z "$1" ]; then
    echo "Please specify the version of the microservice. Format: ###.###.####"
	exit 1
fi

API_VERSION=$1
API_VERSION_DASHES=$( echo ${API_VERSION} | tr '.' '-' ) 
API_NAME="aiRegression"
AWS_APIGW_ID="[censored]"

aws apigateway put-rest-api --rest-api-id $AWS_APIGW_ID --mode overwrite --body "fileb://C:\Coinfarm ventures\Trading bot\labeling\ai-regression-server\openapi\\${API_NAME}-${API_VERSION}_OpenAPISchema-OAS3.0_AutoGenerated.json" --no-cli-pager
sleep 5
aws apigateway create-deployment --rest-api-id $AWS_APIGW_ID --region us-east-2 --stage-name DEV_$API_VERSION_DASHES
sleep 5
aws apigateway create-deployment --rest-api-id $AWS_APIGW_ID --region us-east-2 --stage-name LATEST
